### ISSUE TITLE
Stoneblock 2 crashed citing Framland - dump follows

### ISSUE THREAD

**Issue by BirdTho** [Gaz492/Framland#3]
[https://paste.dimdev.org/oxodekocuj.mccrash](https://paste.dimdev.org/oxodekocuj.mccrash)

**Comment by wally314garcia** [comment]
https://paste.dimdev.org/uqavonawit.mccrash

**Comment by Draylynn** [comment]
https://paste.dimdev.org/umumidicuw.mccrash

**Comment by jnwebster** [comment]
https://paste.dimdev.org/ozemocujef.mccrash

**Comment by Sunekaer** [comment]
https://paste.feed-the-beast.com/view/2a332299

**Comment by BirdTho** [comment]
Yay!
